function fig = plot_transmitarray_geometry_3d()
%PLOT_TRANSMITARRAY_GEOMETRY_3D Display the feed/array/beam geometry.

paths = visualization_paths();
elementFile = fullfile(paths.geometryData, "transmitarray_elements.csv");
referenceFile = fullfile(paths.geometryData, "geometry_references.csv");
assert(isfile(elementFile), "Missing data file: %s", elementFile);
assert(isfile(referenceFile), "Missing data file: %s", referenceFile);

elements = readtable(elementFile);
references = readtable(referenceFile, "TextType", "string");

fprintf("Transmitarray element data:\n");
disp(elements);
fprintf("Geometry reference data:\n");
disp(references);

arrayCenter = readPoint(references, "array_center");
feedPosition = readPoint(references, "feed");
selectedElement = readPoint(references, "selected_element");
mainBeam = readDirection(references, "main_beam");
observation = readDirection(references, "observation");

xValues = unique(elements.x, "sorted");
yValues = unique(elements.y, "sorted");
[xGrid, yGrid] = meshgrid(xValues, yValues);
zGrid = repmat(elements.z(1), size(xGrid));

fig = figure( ...
    "Name", "3D Transmitarray Acquisition Geometry", ...
    "Color", "white", ...
    "Position", [80, 50, 1150, 850]);
axisHandle = axes(fig);
hold(axisHandle, "on");

surfaceHandle = surf( ...
    axisHandle, xGrid, yGrid, zGrid, ...
    "FaceColor", [0.69, 0.77, 0.87], ...
    "FaceAlpha", 0.22, ...
    "EdgeColor", [0.27, 0.51, 0.71], ...
    "HandleVisibility", "off");
scatter3( ...
    axisHandle, elements.x, elements.y, elements.z, ...
    28, [0.0, 0.0, 0.5], "filled", ...
    "DisplayName", sprintf("Transmitarray elements (%d x %d)", numel(yValues), numel(xValues)));
scatter3(axisHandle, feedPosition(1), feedPosition(2), feedPosition(3), ...
    130, "d", "filled", "MarkerFaceColor", [0.85, 0.15, 0.15], "DisplayName", "Feed");
scatter3(axisHandle, selectedElement(1), selectedElement(2), selectedElement(3), ...
    100, "s", "filled", "MarkerFaceColor", "black", "DisplayName", "Selected (m,n) element");
plot3( ...
    axisHandle, ...
    [feedPosition(1), selectedElement(1)], ...
    [feedPosition(2), selectedElement(2)], ...
    [feedPosition(3), selectedElement(3)], ...
    "-", "Color", [0.85, 0.15, 0.15], "LineWidth", 1.8, "DisplayName", "Feed path");
quiver3( ...
    axisHandle, arrayCenter(1), arrayCenter(2), arrayCenter(3), ...
    mainBeam(1), mainBeam(2), mainBeam(3), 0, ...
    "Color", [0.95, 0.50, 0.05], "LineWidth", 2.6, "MaxHeadSize", 0.12, ...
    "DisplayName", "Main beam");
quiver3( ...
    axisHandle, arrayCenter(1), arrayCenter(2), arrayCenter(3), ...
    observation(1), observation(2), observation(3), 0, ...
    "Color", [0.10, 0.55, 0.20], "LineWidth", 2.3, "MaxHeadSize", 0.12, ...
    "DisplayName", "Observation direction");

beamLength = norm(mainBeam);
beamAxis = mainBeam / beamLength;
beamBasis1 = [1.0, 0.0, 0.0];
beamBasis2 = cross(beamAxis, beamBasis1);
beamBasis2 = beamBasis2 / norm(beamBasis2);
[beamDistance, beamAzimuth] = meshgrid( ...
    linspace(0.0, 0.82 * beamLength, 36), ...
    linspace(0.0, 2.0 * pi, 48));
beamRadius = 0.14 * beamDistance;
beamX = arrayCenter(1) + beamAxis(1) .* beamDistance + beamRadius .* ( ...
    beamBasis1(1) .* cos(beamAzimuth) + beamBasis2(1) .* sin(beamAzimuth));
beamY = arrayCenter(2) + beamAxis(2) .* beamDistance + beamRadius .* ( ...
    beamBasis1(2) .* cos(beamAzimuth) + beamBasis2(2) .* sin(beamAzimuth));
beamZ = arrayCenter(3) + beamAxis(3) .* beamDistance + beamRadius .* ( ...
    beamBasis1(3) .* cos(beamAzimuth) + beamBasis2(3) .* sin(beamAzimuth));
surf( ...
    axisHandle, beamX, beamY, beamZ, ...
    "FaceColor", [0.95, 0.50, 0.05], ...
    "FaceAlpha", 0.16, ...
    "EdgeColor", "none", ...
    "HandleVisibility", "off");

xlim(axisHandle, [-5, 5]);
ylim(axisHandle, [-30, 20]);
zlim(axisHandle, [0, 55]);
pbaspect(axisHandle, [10, 50, 55]);
xlabel(axisHandle, "X");
ylabel(axisHandle, "Y");
zlabel(axisHandle, "Z");
title(axisHandle, "3D Transmitarray Radiation-Pattern Acquisition Geometry");
grid(axisHandle, "on");
view(axisHandle, -58, 23);
legend(axisHandle, "Location", "eastoutside");

outputFile = fullfile(paths.figures, "matlab_transmitarray_acquisition_geometry_3d.png");
exportgraphics(fig, outputFile, "Resolution", 220);
fprintf("Saved: %s\n", outputFile);
end

function point = readPoint(references, name)
selection = string(references.name) == name;
assert(nnz(selection) == 1, "Expected one point named %s", name);
point = [references.x(selection), references.y(selection), references.z(selection)];
end

function direction = readDirection(references, name)
selection = string(references.name) == name;
assert(nnz(selection) == 1, "Expected one vector named %s", name);
direction = [references.dx(selection), references.dy(selection), references.dz(selection)];
end
